//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonDat
    {
        public string VAT { get; set; }
        public int idDV { get; set; }
        public int idDonDat { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual DonDat DonDat { get; set; }
    }
}
