//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichVu()
        {
            this.ChiTietDonDats = new HashSet<ChiTietDonDat>();
        }
    
        public int id { get; set; }
        public string Ten { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public byte MaTinh { get; set; }
        public string MaXe { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDat> ChiTietDonDats { get; set; }
        public virtual Xe Xe { get; set; }

        internal static object OrderByDescending(Func<object, object> p)
        {
            throw new NotImplementedException();
        }
    }
}
