//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDat()
        {
            this.ChiTietDonDats = new HashSet<ChiTietDonDat>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<bool> TrangThaiThanhToan { get; set; }
        public string MaNV { get; set; }
        public int MaKH { get; set; }
        public string MaXe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDat> ChiTietDonDats { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
