//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DichVuThueXe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonDats = new HashSet<DonDat>();
        }
        [Key]
        public int MaKH { get; set; }
        [Required(ErrorMessage =" Nhập Tên Khách Hàng")]
        public string TenKH { get; set; }
        [Required(ErrorMessage = " Nhập Số CMND")]
        [RegularExpression("^\\d{9,12}$", ErrorMessage = "Số CMND không hợp lệ!")]
        public string CMND { get; set; }
        [Required(ErrorMessage = " Nhập Địa Chỉ")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = " Nhập Số Điện Thoại")]
        [RegularExpression("^\\d{5,11}$", ErrorMessage = "Số điện thoại không hợp lệ!")]
        public string SDT { get; set; }
        [Required(ErrorMessage = " Nhập Email")]
        [RegularExpression("^\\w+@\\w+\\.\\w{2,4}$", ErrorMessage = "Email không hợp lệ!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Nhập Tài Khoản")]
        public string TaiKhoan { get; set; }
        [Required(ErrorMessage ="Nhập Mật Khẩu")]
        [DataType(DataType.Password)]
        public string MatKhau { get; set; }
        [Compare("MatKhau", ErrorMessage = "Mật khẩu không khớp! Vui lòng nhập lại!")]
        [DataType(DataType.Password)]
        public string NhapLaiMatKhau { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDat> DonDats { get; set; }
    }
}
